#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-junit-xml-parser
Version  : 1.0.0
Release  : 1
URL      : https://github.com/Open-MBEE/junit-xml-parser/archive/1.0.0.tar.gz
Source0  : https://github.com/Open-MBEE/junit-xml-parser/archive/1.0.0.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/org/openmbee/junit/junit-xml-parser/1.0.0/junit-xml-parser-1.0.0.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/openmbee/junit/junit-xml-parser/1.0.0/junit-xml-parser-1.0.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-junit-xml-parser-data = %{version}-%{release}
Requires: mvn-junit-xml-parser-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
## Description:
Parses JUnit XML results into POJOs using JAXB.
Example:
```java
import org.openmbee.junit.JUnitMarshalling;
import org.openmbee.junit.model.JUnitTestSuite;

%package data
Summary: data components for the mvn-junit-xml-parser package.
Group: Data

%description data
data components for the mvn-junit-xml-parser package.


%package license
Summary: license components for the mvn-junit-xml-parser package.
Group: Default

%description license
license components for the mvn-junit-xml-parser package.


%prep
%setup -q -n junit-xml-parser-1.0.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-junit-xml-parser
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-junit-xml-parser/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/openmbee/junit/junit-xml-parser/1.0.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/openmbee/junit/junit-xml-parser/1.0.0/junit-xml-parser-1.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/openmbee/junit/junit-xml-parser/1.0.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/openmbee/junit/junit-xml-parser/1.0.0/junit-xml-parser-1.0.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/openmbee/junit/junit-xml-parser/1.0.0/junit-xml-parser-1.0.0.jar
/usr/share/java/.m2/repository/org/openmbee/junit/junit-xml-parser/1.0.0/junit-xml-parser-1.0.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-junit-xml-parser/LICENSE
